# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('published_date', models.DateTimeField(editable=False)),
                ('path', models.CharField(max_length=128)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization')),
                ('sex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('published_date', models.DateTimeField(editable=False)),
                ('path', models.CharField(max_length=128)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Teacher'),
        ),
        migrations.AddField(
            model_name='classification',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
    ]
