# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
