# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0003_auto_20180129_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(max_length=64, verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization', verbose_name='所属ID'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='classification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification', verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='配布ID'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='name',
            field=models.CharField(max_length=64, verbose_name='ファイル名'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization', verbose_name='所属ID'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='path',
            field=models.CharField(max_length=255, verbose_name='ファイルパス'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='配布者'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization', verbose_name='所属ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='所属ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=64, verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他')], max_length=4, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='classification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification', verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='提出ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=64, verbose_name='ファイル名'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization', verbose_name='所属ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='path',
            field=models.CharField(max_length=255, verbose_name='ファイルパス'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提出者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=64, verbose_name='課題ファイル名'),
        ),
        migrations.AlterField(
            model_name='task',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization', verbose_name='所属ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='課題説明'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='課題提出者'),
        ),
    ]
