language: python

python:
  - "3.6"

services:
  - postgresql

env:
  - DJANGO=django==1.11

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test;'

script:
  - python -Wall manage.py test

