language: python

python:
  - "3.6"

services:
  - postgresql

env:
  - DJANGO=1.11 DB=postgres

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_travis;' -U postgres

script:
  - python -Wall manage.py test

