# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('id', models.IntegerField(primary_key=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('id', models.IntegerField(primary_key=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('id', models.IntegerField(primary_key=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('id', models.IntegerField(primary_key=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='submission_form.Teacher')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=64)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('path', models.CharField(max_length=128)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='submission_form.Student')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=64)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('path', models.CharField(max_length=128)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='sex_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Sex'),
        ),
    ]
