# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('submission_form', '0001_initial'), ('submission_form', '0002_auto_20171116_1924'), ('submission_form', '0003_auto_20171116_1924'), ('submission_form', '0004_auto_20171116_2252'), ('submission_form', '0005_auto_20171116_2336')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('id', models.IntegerField(primary_key=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization')),
                ('name', models.CharField(max_length=64)),
                ('id', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('id', models.IntegerField(primary_key=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_form.Organization')),
                ('id', models.IntegerField(primary_key=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Teacher')),
                ('name', models.CharField(max_length=64)),
                ('published_date', models.DateTimeField(editable=False)),
                ('path', models.CharField(max_length=128)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Student')),
                ('name', models.CharField(max_length=64)),
                ('published_date', models.DateTimeField(editable=False)),
                ('path', models.CharField(max_length=128)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Classification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='sex_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Sex'),
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='id',
            new_name='my_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='my_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='my_id',
        ),
        migrations.AlterField(
            model_name='classification',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='submission_form.Organization'),
        ),
        migrations.RemoveField(
            model_name='classification',
            name='my_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='my_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='my_id',
        ),
        migrations.AddField(
            model_name='classification',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='uuid',
            new_name='id',
        ),
    ]
