# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0002_auto_20171116_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='submission_form.Organization'),
        ),
    ]
