# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0003_auto_20171116_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='my_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='my_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='my_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='my_id',
        ),
        migrations.AddField(
            model_name='classification',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='published_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='published_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_form.Organization'),
        ),
    ]
