# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0004_auto_20171116_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='uuid',
        ),
        migrations.AddField(
            model_name='distribution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
